apiVersion: v2
name: opentelemetry-operator
version: 0.3.3
description: OpenTelemetry Operator Helm chart for Kubernetes
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/pluralsh/plural-helm-charts
maintainers:
  - name: DavidSpek
icon: https://raw.githubusercontent.com/cncf/artwork/a718fa97fffec1b9fd14147682e9e3ac0c8817cb/projects/opentelemetry/icon/color/opentelemetry-icon-color.png
appVersion: 0.33.0
