apiVersion: v2
name: airbyte
description: Helm chart to deploy airbyte
type: application
version: 0.3.0
appVersion: "0.32.5-alpha"

dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
    - bitnami-common
  version: 1.x.x
- condition: postgresql.enabled
  name: postgresql
  version: 10.x.x
  repository: https://charts.bitnami.com/bitnami
- condition: minio.enabled
  name: minio
  version: 7.x.x
  repository: https://charts.bitnami.com/bitnami
