apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hasura.fullname" . }}
  labels:
  {{- include "hasura.labels" . | nindent 4 }}
type: Opaque
stringData:
  HASURA_GRAPHQL_DATABASE_USERNAME: {{ .Values.database.username | quote }}
  {{- if empty .Values.database.secret.name }}
  HASURA_GRAPHQL_DATABASE_PASSWORD: {{ .Values.database.password | quote }}
  {{- end }}
  HASURA_GRAPHQL_DATABASE_HOSTNAME: {{ .Values.database.hostname | quote }}
  HASURA_GRAPHQL_DATABASE_PORT: {{ .Values.database.port | quote }}
  HASURA_GRAPHQL_DATABASE_NAME: {{ .Values.database.name | quote }}
  HASURA_GRAPHQL_ADMIN_SECRET: {{ .Values.adminSecret | quote }}
{{- if .Values.jwtSecret }}
  HASURA_GRAPHQL_JWT_SECRET: {{ .Values.jwtSecret | toJson | quote }}
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: {{ .Values.unauthorizedRole | quote }}
{{- end }}
{{- with .Values.extraEnvVarsSecret }}
  {{- tpl ( . | toYaml) $ | nindent 2 }}
{{- end }}