apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "etcd-operator.fullname" . }}-controller
  labels:
    {{- include "etcd-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "etcd-operator.controllerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "etcd-operator.controllerSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "etcd-operator.serviceAccountName" . }}-controller
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-controller
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.controller.repository }}:{{ .Values.image.controller.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.controller.pullPolicy }}
          command:
            - /manager
          args:
            - --enable-leader-election
            - --proxy-url={{ include "etcd-operator.fullname" . }}-proxy.{{ .Release.Namespace }}.svc
          env:
            - name: DISABLE_WEBHOOKS
              value: "true"
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: metrics
          # readinessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: metrics
          resources:
            {{- toYaml .Values.resources.controller | nindent 12 }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
