apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "etcd-operator.fullname" . }}-leader-election-role-binding
  labels: {{- include "etcd-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "etcd-operator.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "etcd-operator.serviceAccountName" . }}-controller
    namespace: {{ .Release.Namespace}}
