apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd-operator.fullname" . }}-controller-metrics
  labels:
    {{- include "etcd-operator.controllerSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "etcd-operator.controllerSelectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd-operator.fullname" . }}-proxy
  labels:
    {{- include "etcd-operator.proxySelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: grpc-api
  selector:
    {{- include "etcd-operator.proxySelectorLabels" . | nindent 4 }}
