apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "mysql-operator.fullname" . }}-statefulset-cleanup
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ template "mysql-operator.fullname" . }}-statefulset-cleanup
    spec:
      serviceAccountName: {{ include "mysql-operator.serviceAccountName" . }}
      containers:
        - name: kubectl
          image: bitnami/kubectl
          imagePullPolicy: "IfNotPresent"
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          command:
          - /bin/sh
          - -c
          - kubectl delete statefulset -n ${NAMESPACE} {{ include "mysql-operator.fullname" . }};
      restartPolicy: OnFailure
