apiVersion: v2
name: tempo-distributed
description: Grafana Tempo in MicroService mode
type: application
version: 0.9.16
appVersion: 1.1.0
engine: gotpl
home: https://grafana.com/docs/tempo/latest/
icon: https://raw.githubusercontent.com/grafana/tempo/master/docs/tempo/website/logo_and_name.png
sources:
  - https://github.com/grafana/tempo
maintainers:
  - name: DavidSpek
